# Je suis entrain de mettre en place ma premier ci/cd

name: Laravel CI/CD

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on:  ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: set up PHP
        uses: shivammathur/setup-php@v2
        with: 
          php-version:  '8.2'
      
      - name:  Install dependencies
        run: |
          composer install --no-progress --prefer-dist
          npm install

      - name: Run migrations
        run:  php artisan migrate --env=testing --force

      - name: Run tests
        run: php artisan test

      - name: Compile TailwindCss
        run: npm run build

      # - name: Deploy to production
      #   if: github.ref == 'refs/heads/main'
      #   run: |
         